// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewwyerdpyjitriibbgbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3d3llcmRweWppdHJpaWJiZ2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDI0MTEsImV4cCI6MjA1OTI3ODQxMX0.nlSUK0GNaQNnIfyAzL0u90_k4fbK5Bm7X_XtfVvWxCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);